export const CATEGORY_SLUG_TO_NAME: Record<string, string> = {
  "javascript-typescript": "Javascript/Typescript",
  react: "React",
  css: "CSS",
  database: "Database",
  nodejs: "NodeJS",
  security: "Security",
  tips: "Tips",
  tools: "Tools",
  "interview-question": "Interview Question",
  "design-patterns": "Design Patterns",
  aws: "AWS",
  nosql: "NoSQL",
  ruby: "Ruby",
  "architecture-and-design": "Architecture & Design",
  technology: "All Topics",
  "ai-machine-learning-en": "AI & Machine Learning",
  "architecture-and-design-en": "Architecture & Design",
  "tools-en": "Tools",
};

export const CATEGORY_SLUG_TO_ID: Record<string, number> = {
  "javascript-typescript": 151,
  react: 343,
  css: 276,
  database: 77,
  nodejs: 92,
  security: 176,
  tips: 53,
  tools: 177,
  "interview-question": 234,
  "design-patterns": 171,
  aws: 62,
  nosql: 155,
  ruby: 63,
  "architecture-and-design": 48,
  technology: 6,
  "ai-machine-learning-en": 926,
  "architecture-and-design-en": 958,
  "tools-en": 929,
};
