name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use the version you need

    - name: Deploy to EC2
      env:
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
      run: |
        echo "Deploying to EC2..."
        echo "$EC2_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
          set -e
          cd $PROJECT_PATH
          git pull origin main
          npm install
          npm run build
          pm2 restart portfolio-latest || pm2 start npm --name "portfolio-latest" -- start
        EOF